# Generated by Django 5.0.1 on 2024-01-11 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphAPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HasRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='GraphAPI.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_read', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
