# Generated by Django 5.0.1 on 2024-01-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphAPI', '0002_hasread'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fiction',
            field=models.BooleanField(default=False),
        ),
    ]
