# Generated by Django 5.0.1 on 2024-01-17 08:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GraphAPI', '0003_book_fiction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hasread',
            unique_together={('user', 'book')},
        ),
    ]
